# Generated by Django 6.0.7 on 2026-07-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('score_minimum', models.IntegerField(default=50)),
                ('lecon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('choix', models.JSONField()),
                ('reponse_correcte', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.FloatField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('niveau', models.IntegerField(default=1)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.parcours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='accounts.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'parcours')},
            },
        ),
    ]
