# Generated by Django 6.0.7 on 2026-07-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_parcours_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='parcours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='courses.parcours'),
            preserve_default=False,
        ),
    ]
