# Generated by Django 6.0.7 on 2026-07-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_certificat_parcours'),
        ('courses', '0002_parcours_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificat',
            unique_together={('utilisateur', 'parcours')},
        ),
    ]
