# Generated by Django 6.0.7 on 2026-07-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(max_length=20)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours_geres', to='accounts.administrateur')),
                ('apprenants', models.ManyToManyField(blank=True, related_name='parcours_suivis', to='accounts.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playgrounds', to='courses.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualisations', to='courses.lecon')),
            ],
        ),
    ]
