# Generated by Django 6.0.7 on 2026-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
