# Generated by Django 6.0.7 on 2026-07-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_certificat_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierVirtuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('dir', 'Dossier'), ('file', 'Fichier')], max_length=10)),
                ('contenu', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_virtuels', to='accounts.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'chemin')},
            },
        ),
    ]
